Ecommerce.Presentaion/Controllers/FacilityController.cs
using Ecommerce.Application.Services;
using Ecommerce.Application.Services.ServicesCategories;
using Ecommerce.DTOs.Facility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce.Presentaion.Controllers
{
    [Authorize(Roles = "admin")]
    public class FacilityController : Controller
    {
        private readonly IFacillityService facilityService;
        private readonly ISubCategoryServices subCategoryService;
        public FacilityController(ISubCategoryServices _subCategoryService,IFacillityService _facillityService)
        {
            facilityService = _facillityService;
            subCategoryService = _subCategoryService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetALl()
        {
            var facilities = await facilityService.GetAllAsync();
            return View(facilities);
        }
        public async Task<IActionResult> Create()
        {
            var subcategories = await subCategoryService.GetAllSubCategoriesAsync();
            ViewBag.subcategories = subcategories;
            //CreatorUpdateFacilityDTO  facilityDTO = new CreatorUpdateFacilityDTO();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreatorUpdateFacilityDTO facilityDTO)
        {
            if (ModelState.IsValid)
            {
                var res = await facilityService.CreateAsync(facilityDTO);
                if (res.IsSuccess)
                {
                    return RedirectToAction("GetALl");
                }
                else
                {
                    var subcategories = await subCategoryService.GetAllSubCategoriesAsync();
                    ViewBag.subcategories = subcategories;
                    return View();
                }
                //return RedirectToAction("GetALl");
            }
            else
            {
                var subcategories = await subCategoryService.GetAllSubCategoriesAsync();
                ViewBag.subcategories = subcategories;
                return View();
            }
        }
        public async Task<IActionResult> Update(int id)
        {
            var subcategories = await subCategoryService.GetAllSubCategoriesAsync();
            ViewBag.subcategories = subcategories;
            var facility = await facilityService.GetByIdAsync(id);
            return View(facility);
        }

        [HttpPost]
        public async Task<IActionResult> Update(CreatorUpdateFacilityDTO facilityDTO)
        {
            if (ModelState.IsValid)
            {
                var res = await facilityService.UpdateAsync(facilityDTO);
                if (res.IsSuccess)
                {
                    return RedirectToAction("GetALl");
                }
                return RedirectToAction("GetALl");
            }
            else
            {
                var subcategories = await subCategoryService.GetAllSubCategoriesAsync();
                ViewBag.subcategories = subcategories;
                return View(facilityDTO);
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            await facilityService.DeleteAsync(id);
            return RedirectToAction("GetALl");
        }
    }
}

Ecommerce.Presentaion/Controllers/ProductController.cs
using AutoMapper;
using Ecommerce.Application.Services;
using Ecommerce.Application.Services.Product_Facility;
using Ecommerce.Application.Services.ServicesCategories;
using Ecommerce.DTOs.Facility;
using Ecommerce.DTOs.Product;
using Ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Ecommerce.Presentaion.Controllers
{
    [Authorize(Roles = "admin")]
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        private readonly ISubCategoryServices subCategoryService;
        private readonly ISubCatFacilityService subcatfacilityService;
        private readonly IFacillityService facilityService;
        private readonly IImageService imageService;
        private readonly IProductFacilityServices productfacilityServices;
        public ProductController(ISubCategoryServices _subCategoryService,
            IProductService _productService,
            IImageService _imageService, IProductFacilityServices _productfacilityServices,
            ISubCatFacilityService _subcatfacilityService, IFacillityService _facilityService)
        {
            productService = _productService;
            subCategoryService = _subCategoryService;
            imageService = _imageService;
            subcatfacilityService= _subcatfacilityService;
            facilityService = _facilityService;
            productfacilityServices= _productfacilityServices;
        }
      
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetALlProduct(int PageNumber=1, int Count=10)
        {
            var products = await productService.GetAllAsync(PageNumber,Count);
           
            return View(products);
        }
        public async Task<IActionResult> Create()
        {
            var subcategories = await subCategoryService.GetAllSubCategoriesAsync();
            CreateAndUpdateProductDTO productDTO = new CreateAndUpdateProductDTO();
            ViewBag.subcategories=subcategories;
            return View(productDTO);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateAndUpdateProductDTO productDTO, List<IFormFile> images)
        {
            if (ModelState.IsValid)
            {

                var res=await productService.CreateAsync(productDTO);
               
                if (res.IsSuccess)
                {
                    var imgs = await imageService.UploadImagesAsync(productDTO.ImagesFromFile, res.Entity.Id);

                    PrdFacilitySubCategory PFS = new PrdFacilitySubCategory();
                    PFS.ProductId = res.Entity.Id;

                    



                    for (int i = 0;i < productDTO.SubCategoryIds.Count;i++)
                        PFS.SubcatsIDS.Add(productDTO.SubCategoryIds[i]);

                    if(PFS.SubcatsIDS.Count > 0)
                    {
                      var FaciltyDto = await subcatfacilityService.Getallfacilitybyubcatid(PFS.SubcatsIDS);
                        PFS.FacilityDTO = FaciltyDto;
                      
                    }

                    return View("CreatePrdFacility" , PFS);

                    //await CreatePrdFacility(res.Entity.Id);
                    //return RedirectToAction("CreatePrdFacility", res.Entity.Id);
                    //return RedirectToAction("GetALlProduct");
                }
                return RedirectToAction("GetALlProduct");
            }
            var subcategories = await subCategoryService.GetAllSubCategoriesAsync();
            ViewBag.subcategories = subcategories;
            return View(productDTO);
            
        }
        [HttpGet]
        public async Task<IActionResult> CreatePrdFacility()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePrdFacility(PrdFacilitySubCategory PFS)
        {
            if (ModelState.IsValid)
            {
                var result = (await productfacilityServices.CreatePrdFaciltyAsync(PFS));
                if (result!=null)
                {
                    return RedirectToAction("GetALlProduct");
                }
                else { return View(); }
            }
            else { return View(); }
        }

        public async Task<IActionResult> Update(int id)
        {
            var product = (await productService.GetById(id));
            var subcategories = (await subCategoryService.GetAllSubCategoriesAsync());
            ViewBag.subcategories = subcategories;
            return View(product);
        }


        [HttpPost]
        public async Task<IActionResult> Update(CreateAndUpdateProductDTO productDTO)
        {
            if (ModelState.IsValid)
            {
               

                var res = await productService.UpdateAsync(productDTO);
                if (res.IsSuccess)
                {

                    var imgs = await imageService.UploadImagesAsync(productDTO.ImagesFromFile, res.Entity.Id);
                    PrdFacilitySubCategory PFS = new PrdFacilitySubCategory();
                    PFS.ProductId = res.Entity.Id;
                    for (int i = 0; i < productDTO.SubCategoryIds.Count; i++)
                        PFS.SubcatsIDS.Add(productDTO.SubCategoryIds[i]);

                  
                        var prdFacilities = await productfacilityServices.GetFacilitesByPrdIdAsync(res.Entity.Id);
                        PFS.Values_En.AddRange(prdFacilities.Values_En);
                        PFS.Values_Ar.AddRange(prdFacilities.Values_Ar);
                      

                    if (PFS.SubcatsIDS.Count > 0)
                    {
                        var FaciltyDto = await subcatfacilityService.Getallfacilitybyubcatid(PFS.SubcatsIDS);
                        PFS.FacilityDTO = FaciltyDto;
                    }
                    return View("UpdateProductFacilty", PFS);
               
                }
                return RedirectToAction("GetALlProduct");
            }
            var subcategories = await subCategoryService.GetAllSubCategoriesAsync();
            ViewBag.subcategories = subcategories;
            return View(productDTO);
            
        }
        [HttpGet]
        public async Task<IActionResult> UpdateProductFacilty() 
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateProductFacilty(PrdFacilitySubCategory PFS)
        {

            if (ModelState.IsValid)
            {
                var result = (await productfacilityServices.UpdatePrdFaciltyAsync(PFS));
                if (result != null)
                {
                    return RedirectToAction("GetALlProduct");
                }
                else { return View(); }
            }
            else { return View(); }
        }
        public async Task<IActionResult> SearchProduct(string? ProductName, decimal? price,int PageNumber = 1, int Count = 10)
        {
            var product = await productService.SearchByNameAsync(PageNumber,Count,ProductName,price);
            return View("GetALlProduct",product);
        }
        public async Task<IActionResult> Delete(int id)
        {
             var result=await productService.DeleteAsync(id);
            if (!result.IsSuccess)
            {
                TempData["ErrorMessage"] = result.Message;
            }
            return RedirectToAction("GetALlProduct");
        }
    }
}

Ecommerce.Presentaion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Walmart Dashboard</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
    <link href="~/images/walmart-logo.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">
              
  <!-- Google Fonts -->
  <link href="~/https://fonts.gstatic.com" rel="preconnect">
  <link href="~/https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
              
  <!-- Vendor ~/CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
            <a href="/Home/Index" class="logo d-flex align-items-center">
                <img src="~/images/walmart-logo.png" alt="">
                <span class="d-lg-blodck" style="font-family:cursive">Walmart</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

   

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

       
 <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="~/images/walmart-logo.png" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">@User.Identity.Name</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>@User.Identity.Name</h6>
              <span>Admin</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="/Account/Profile">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
                <a class="dropdown-item d-flex align-items-center" href="/Account/ResetPassword">
                <i class="bi bi-gear"></i>
                <span>Reset Password</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

          @*   <li>
              <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                <i class="bi bi-question-circle"></i>
                <span>Need Help?</span>
              </a>
            </li> *@
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="/Account/SignOut">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
                <a class="nav-link " href="/Dashboard/index">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

            <li class="nav-heading">Pages</li>
            
      <li class="nav-item">
                <a class="nav-link collapsed" asp-controller="Product" asp-action="GetALlProduct">

                    <i><img src="~/images/walmart-logo-png-27972-windows.ico" width="20px" height="20px" /></i>
                    <span>Products</span>
        </a>
      </li>
      <!-- End Products Page Nav -->
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Facility" asp-action="GetALl">

                <i><img src="~/images/walmart-logo-png-27972-windows.ico" width="20px" height="20px" /></i>
                    <span>Specification</span>
            </a>
        </li>
             <!-- End Facilities Page Nav -->
      <li class="nav-item">
                <a class="nav-link collapsed" href="/Category/AllCategories">
                    <i><img src="~/images/walmart-logo-png-27972-windows.ico" width="20px" height="20px" /></i>
          <span>Categories</span>
        </a>
      </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="/SubCategory/AllSubCategories">
                    <i><img src="~/images/walmart-logo-png-27972-windows.ico" width="20px" height="20px" /></i>
                    <span>SubCategories</span>
                </a>
            </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="/Order/GetAll">
                    <i><img src="~/images/walmart-logo-png-27972-windows.ico" width="20px" height="20px" /></i>
          <span>Orders</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="/user/Index">
                    <i><img src="~/images/walmart-logo-png-27972-windows.ico" width="20px" height="20px" /></i>
          <span>Users</span>
        </a>
      </li>
   @*    <li class="nav-item">
                <a class="nav-link collapsed" asp-controller="Shipment" asp-action="Index">
                    <i><img src="~/images/walmart-logo-png-27972-windows.ico" width="20px" height="20px" /></i>
          <span>Shipment</span>
        </a>
      </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-controller="Payment" asp-action="Index">
                    <i><img src="~/images/walmart-logo-png-27972-windows.ico" width="20px" height="20px" /></i>
                    <span>Payment</span>
                </a>
            </li>
 *@

      <!-- End Contact Page Nav -->

        <li class="nav-item">
                <a class="nav-link collapsed" href="/Account/Profile">
                <i class="bi bi-person"></i>
                <span>Profile</span>
            </a>
        </li><!-- End Profile Page Nav -->

      <li class="nav-item">
                <a class="nav-link collapsed" href="/Account/AddAdmin">
          <i class="bi bi-card-list"></i>
          <span>Add Admin</span>
        </a>
      </li><!-- End Register Page Nav -->

     @*  <li class="nav-item">
                <a class="nav-link collapsed" href="/Account/Login">
          <i class="bi bi-box-arrow-in-right"></i>
          <span>Login</span>
        </a>
      </li><!-- End Login Page Nav --> *@
    </ul>

  </aside>
  <!-- End Sidebar-->

  <main id="main" >
      <div class="container">
        @RenderBody()
      </div>

  </main>
  <!-- End #main -->
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>Team 4 Walmert </span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      @* Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> *@
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
  <script src="~/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/assets/vendor/quill/quill.js"></script>
  <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>
  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>